// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 2027713919;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__db_api__create_paciente_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "create_paciente",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_paciente = <crate::db::models::NuevoPaciente>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::db_api::create_paciente(api_paciente)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__db_api__create_sesion_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "create_sesion",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_sesion = <crate::db::models::NuevaSesion>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::db_api::create_sesion(api_sesion)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__db_api__create_tratamiento_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "create_tratamiento",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_tratamiento =
                <crate::db::models::NuevoTratamiento>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::db_api::create_tratamiento(api_tratamiento)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__db_api__deactivate_paciente_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "deactivate_paciente",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_id = <i64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::db_api::deactivate_paciente(api_id)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__db_api__get_paciente_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_paciente",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_id = <i64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::db_api::get_paciente(api_id)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__db_api__get_sesion_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_sesion",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_id = <i64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::db_api::get_sesion(api_id)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__simple__greet_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "greet",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_name = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::simple::greet(api_name))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::simple::init_app();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__db_api__init_database_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_database",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_db_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::db_api::init_database(api_db_path)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__db_api__list_pacientes_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "list_pacientes",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_search = <Option<String>>::sse_decode(&mut deserializer);
            let api_page = <i32>::sse_decode(&mut deserializer);
            let api_page_size = <i32>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok =
                        crate::api::db_api::list_pacientes(api_search, api_page, api_page_size)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__db_api__list_sesiones_by_paciente_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "list_sesiones_by_paciente",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_paciente_id = <i64>::sse_decode(&mut deserializer);
            let api_page = <i32>::sse_decode(&mut deserializer);
            let api_page_size = <i32>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::db_api::list_sesiones_by_paciente(
                        api_paciente_id,
                        api_page,
                        api_page_size,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__db_api__list_tratamientos_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "list_tratamientos",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::db_api::list_tratamientos()?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__db_api__update_paciente_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "update_paciente",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_paciente =
                <crate::db::models::ActualizarPaciente>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::db_api::update_paciente(api_paciente)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__db_api__update_sesion_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "update_sesion",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_sesion = <crate::db::models::ActualizarSesion>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::db_api::update_sesion(api_sesion)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__db_api__update_tratamiento_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "update_tratamiento",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_tratamiento =
                <crate::db::models::ActualizarTratamiento>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::db_api::update_tratamiento(api_tratamiento)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::db::models::ActualizarPaciente {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <i64>::sse_decode(deserializer);
        let mut var_nombre = <String>::sse_decode(deserializer);
        let mut var_apellido = <String>::sse_decode(deserializer);
        let mut var_fechaNacimiento = <Option<String>>::sse_decode(deserializer);
        let mut var_telefono = <Option<String>>::sse_decode(deserializer);
        let mut var_email = <Option<String>>::sse_decode(deserializer);
        let mut var_direccion = <Option<String>>::sse_decode(deserializer);
        let mut var_notasGenerales = <Option<String>>::sse_decode(deserializer);
        let mut var_alergias = <Option<String>>::sse_decode(deserializer);
        let mut var_condicionesMedicas = <Option<String>>::sse_decode(deserializer);
        return crate::db::models::ActualizarPaciente {
            id: var_id,
            nombre: var_nombre,
            apellido: var_apellido,
            fecha_nacimiento: var_fechaNacimiento,
            telefono: var_telefono,
            email: var_email,
            direccion: var_direccion,
            notas_generales: var_notasGenerales,
            alergias: var_alergias,
            condiciones_medicas: var_condicionesMedicas,
        };
    }
}

impl SseDecode for crate::db::models::ActualizarSesion {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <i64>::sse_decode(deserializer);
        let mut var_tratamientoId = <Option<i64>>::sse_decode(deserializer);
        let mut var_fecha = <String>::sse_decode(deserializer);
        let mut var_notasSesion = <Option<String>>::sse_decode(deserializer);
        let mut var_observaciones = <Option<String>>::sse_decode(deserializer);
        let mut var_productosUsados = <Option<String>>::sse_decode(deserializer);
        let mut var_precioCobrado = <Option<f64>>::sse_decode(deserializer);
        let mut var_pagado = <bool>::sse_decode(deserializer);
        return crate::db::models::ActualizarSesion {
            id: var_id,
            tratamiento_id: var_tratamientoId,
            fecha: var_fecha,
            notas_sesion: var_notasSesion,
            observaciones: var_observaciones,
            productos_usados: var_productosUsados,
            precio_cobrado: var_precioCobrado,
            pagado: var_pagado,
        };
    }
}

impl SseDecode for crate::db::models::ActualizarTratamiento {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <i64>::sse_decode(deserializer);
        let mut var_nombre = <String>::sse_decode(deserializer);
        let mut var_descripcion = <Option<String>>::sse_decode(deserializer);
        let mut var_duracionMin = <Option<i64>>::sse_decode(deserializer);
        let mut var_precio = <Option<f64>>::sse_decode(deserializer);
        return crate::db::models::ActualizarTratamiento {
            id: var_id,
            nombre: var_nombre,
            descripcion: var_descripcion,
            duracion_min: var_duracionMin,
            precio: var_precio,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<crate::db::models::Paciente> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::db::models::Paciente>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::db::models::Sesion> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::db::models::Sesion>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::db::models::Tratamiento> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::db::models::Tratamiento>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::db::models::NuevaSesion {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_pacienteId = <i64>::sse_decode(deserializer);
        let mut var_tratamientoId = <Option<i64>>::sse_decode(deserializer);
        let mut var_fecha = <String>::sse_decode(deserializer);
        let mut var_notasSesion = <Option<String>>::sse_decode(deserializer);
        let mut var_observaciones = <Option<String>>::sse_decode(deserializer);
        let mut var_productosUsados = <Option<String>>::sse_decode(deserializer);
        let mut var_precioCobrado = <Option<f64>>::sse_decode(deserializer);
        let mut var_pagado = <bool>::sse_decode(deserializer);
        return crate::db::models::NuevaSesion {
            paciente_id: var_pacienteId,
            tratamiento_id: var_tratamientoId,
            fecha: var_fecha,
            notas_sesion: var_notasSesion,
            observaciones: var_observaciones,
            productos_usados: var_productosUsados,
            precio_cobrado: var_precioCobrado,
            pagado: var_pagado,
        };
    }
}

impl SseDecode for crate::db::models::NuevoPaciente {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_nombre = <String>::sse_decode(deserializer);
        let mut var_apellido = <String>::sse_decode(deserializer);
        let mut var_fechaNacimiento = <Option<String>>::sse_decode(deserializer);
        let mut var_telefono = <Option<String>>::sse_decode(deserializer);
        let mut var_email = <Option<String>>::sse_decode(deserializer);
        let mut var_direccion = <Option<String>>::sse_decode(deserializer);
        let mut var_notasGenerales = <Option<String>>::sse_decode(deserializer);
        let mut var_alergias = <Option<String>>::sse_decode(deserializer);
        let mut var_condicionesMedicas = <Option<String>>::sse_decode(deserializer);
        return crate::db::models::NuevoPaciente {
            nombre: var_nombre,
            apellido: var_apellido,
            fecha_nacimiento: var_fechaNacimiento,
            telefono: var_telefono,
            email: var_email,
            direccion: var_direccion,
            notas_generales: var_notasGenerales,
            alergias: var_alergias,
            condiciones_medicas: var_condicionesMedicas,
        };
    }
}

impl SseDecode for crate::db::models::NuevoTratamiento {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_nombre = <String>::sse_decode(deserializer);
        let mut var_descripcion = <Option<String>>::sse_decode(deserializer);
        let mut var_duracionMin = <Option<i64>>::sse_decode(deserializer);
        let mut var_precio = <Option<f64>>::sse_decode(deserializer);
        return crate::db::models::NuevoTratamiento {
            nombre: var_nombre,
            descripcion: var_descripcion,
            duracion_min: var_duracionMin,
            precio: var_precio,
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<f64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<i64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::db::models::Paciente> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::db::models::Paciente>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::db::models::Sesion> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::db::models::Sesion>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::db::models::Paciente {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <i64>::sse_decode(deserializer);
        let mut var_nombre = <String>::sse_decode(deserializer);
        let mut var_apellido = <String>::sse_decode(deserializer);
        let mut var_fechaNacimiento = <Option<String>>::sse_decode(deserializer);
        let mut var_telefono = <Option<String>>::sse_decode(deserializer);
        let mut var_email = <Option<String>>::sse_decode(deserializer);
        let mut var_direccion = <Option<String>>::sse_decode(deserializer);
        let mut var_notasGenerales = <Option<String>>::sse_decode(deserializer);
        let mut var_alergias = <Option<String>>::sse_decode(deserializer);
        let mut var_condicionesMedicas = <Option<String>>::sse_decode(deserializer);
        let mut var_fechaRegistro = <String>::sse_decode(deserializer);
        let mut var_activo = <bool>::sse_decode(deserializer);
        return crate::db::models::Paciente {
            id: var_id,
            nombre: var_nombre,
            apellido: var_apellido,
            fecha_nacimiento: var_fechaNacimiento,
            telefono: var_telefono,
            email: var_email,
            direccion: var_direccion,
            notas_generales: var_notasGenerales,
            alergias: var_alergias,
            condiciones_medicas: var_condicionesMedicas,
            fecha_registro: var_fechaRegistro,
            activo: var_activo,
        };
    }
}

impl SseDecode for crate::db::models::PaginatedPacientes {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_items = <Vec<crate::db::models::Paciente>>::sse_decode(deserializer);
        let mut var_total = <i64>::sse_decode(deserializer);
        let mut var_page = <i32>::sse_decode(deserializer);
        let mut var_pageSize = <i32>::sse_decode(deserializer);
        return crate::db::models::PaginatedPacientes {
            items: var_items,
            total: var_total,
            page: var_page,
            page_size: var_pageSize,
        };
    }
}

impl SseDecode for crate::db::models::PaginatedSesiones {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_items = <Vec<crate::db::models::Sesion>>::sse_decode(deserializer);
        let mut var_total = <i64>::sse_decode(deserializer);
        let mut var_page = <i32>::sse_decode(deserializer);
        let mut var_pageSize = <i32>::sse_decode(deserializer);
        return crate::db::models::PaginatedSesiones {
            items: var_items,
            total: var_total,
            page: var_page,
            page_size: var_pageSize,
        };
    }
}

impl SseDecode for crate::db::models::Sesion {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <i64>::sse_decode(deserializer);
        let mut var_pacienteId = <i64>::sse_decode(deserializer);
        let mut var_tratamientoId = <Option<i64>>::sse_decode(deserializer);
        let mut var_fecha = <String>::sse_decode(deserializer);
        let mut var_notasSesion = <Option<String>>::sse_decode(deserializer);
        let mut var_observaciones = <Option<String>>::sse_decode(deserializer);
        let mut var_productosUsados = <Option<String>>::sse_decode(deserializer);
        let mut var_precioCobrado = <Option<f64>>::sse_decode(deserializer);
        let mut var_pagado = <bool>::sse_decode(deserializer);
        let mut var_createdAt = <String>::sse_decode(deserializer);
        return crate::db::models::Sesion {
            id: var_id,
            paciente_id: var_pacienteId,
            tratamiento_id: var_tratamientoId,
            fecha: var_fecha,
            notas_sesion: var_notasSesion,
            observaciones: var_observaciones,
            productos_usados: var_productosUsados,
            precio_cobrado: var_precioCobrado,
            pagado: var_pagado,
            created_at: var_createdAt,
        };
    }
}

impl SseDecode for crate::db::models::Tratamiento {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <i64>::sse_decode(deserializer);
        let mut var_nombre = <String>::sse_decode(deserializer);
        let mut var_descripcion = <Option<String>>::sse_decode(deserializer);
        let mut var_duracionMin = <Option<i64>>::sse_decode(deserializer);
        let mut var_precio = <Option<f64>>::sse_decode(deserializer);
        let mut var_activo = <bool>::sse_decode(deserializer);
        return crate::db::models::Tratamiento {
            id: var_id,
            nombre: var_nombre,
            descripcion: var_descripcion,
            duracion_min: var_duracionMin,
            precio: var_precio,
            activo: var_activo,
        };
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__db_api__create_paciente_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__api__db_api__create_sesion_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__api__db_api__create_tratamiento_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__db_api__deactivate_paciente_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__crate__api__db_api__get_paciente_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__api__db_api__get_sesion_impl(port, ptr, rust_vec_len, data_len),
        8 => wire__crate__api__simple__init_app_impl(port, ptr, rust_vec_len, data_len),
        9 => wire__crate__api__db_api__init_database_impl(port, ptr, rust_vec_len, data_len),
        10 => wire__crate__api__db_api__list_pacientes_impl(port, ptr, rust_vec_len, data_len),
        11 => wire__crate__api__db_api__list_sesiones_by_paciente_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        12 => wire__crate__api__db_api__list_tratamientos_impl(port, ptr, rust_vec_len, data_len),
        13 => wire__crate__api__db_api__update_paciente_impl(port, ptr, rust_vec_len, data_len),
        14 => wire__crate__api__db_api__update_sesion_impl(port, ptr, rust_vec_len, data_len),
        15 => wire__crate__api__db_api__update_tratamiento_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        7 => wire__crate__api__simple__greet_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::db::models::ActualizarPaciente {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.nombre.into_into_dart().into_dart(),
            self.apellido.into_into_dart().into_dart(),
            self.fecha_nacimiento.into_into_dart().into_dart(),
            self.telefono.into_into_dart().into_dart(),
            self.email.into_into_dart().into_dart(),
            self.direccion.into_into_dart().into_dart(),
            self.notas_generales.into_into_dart().into_dart(),
            self.alergias.into_into_dart().into_dart(),
            self.condiciones_medicas.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::db::models::ActualizarPaciente
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::db::models::ActualizarPaciente>
    for crate::db::models::ActualizarPaciente
{
    fn into_into_dart(self) -> crate::db::models::ActualizarPaciente {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::db::models::ActualizarSesion {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.tratamiento_id.into_into_dart().into_dart(),
            self.fecha.into_into_dart().into_dart(),
            self.notas_sesion.into_into_dart().into_dart(),
            self.observaciones.into_into_dart().into_dart(),
            self.productos_usados.into_into_dart().into_dart(),
            self.precio_cobrado.into_into_dart().into_dart(),
            self.pagado.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::db::models::ActualizarSesion
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::db::models::ActualizarSesion>
    for crate::db::models::ActualizarSesion
{
    fn into_into_dart(self) -> crate::db::models::ActualizarSesion {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::db::models::ActualizarTratamiento {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.nombre.into_into_dart().into_dart(),
            self.descripcion.into_into_dart().into_dart(),
            self.duracion_min.into_into_dart().into_dart(),
            self.precio.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::db::models::ActualizarTratamiento
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::db::models::ActualizarTratamiento>
    for crate::db::models::ActualizarTratamiento
{
    fn into_into_dart(self) -> crate::db::models::ActualizarTratamiento {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::db::models::NuevaSesion {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.paciente_id.into_into_dart().into_dart(),
            self.tratamiento_id.into_into_dart().into_dart(),
            self.fecha.into_into_dart().into_dart(),
            self.notas_sesion.into_into_dart().into_dart(),
            self.observaciones.into_into_dart().into_dart(),
            self.productos_usados.into_into_dart().into_dart(),
            self.precio_cobrado.into_into_dart().into_dart(),
            self.pagado.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::db::models::NuevaSesion
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::db::models::NuevaSesion>
    for crate::db::models::NuevaSesion
{
    fn into_into_dart(self) -> crate::db::models::NuevaSesion {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::db::models::NuevoPaciente {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.nombre.into_into_dart().into_dart(),
            self.apellido.into_into_dart().into_dart(),
            self.fecha_nacimiento.into_into_dart().into_dart(),
            self.telefono.into_into_dart().into_dart(),
            self.email.into_into_dart().into_dart(),
            self.direccion.into_into_dart().into_dart(),
            self.notas_generales.into_into_dart().into_dart(),
            self.alergias.into_into_dart().into_dart(),
            self.condiciones_medicas.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::db::models::NuevoPaciente
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::db::models::NuevoPaciente>
    for crate::db::models::NuevoPaciente
{
    fn into_into_dart(self) -> crate::db::models::NuevoPaciente {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::db::models::NuevoTratamiento {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.nombre.into_into_dart().into_dart(),
            self.descripcion.into_into_dart().into_dart(),
            self.duracion_min.into_into_dart().into_dart(),
            self.precio.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::db::models::NuevoTratamiento
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::db::models::NuevoTratamiento>
    for crate::db::models::NuevoTratamiento
{
    fn into_into_dart(self) -> crate::db::models::NuevoTratamiento {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::db::models::Paciente {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.nombre.into_into_dart().into_dart(),
            self.apellido.into_into_dart().into_dart(),
            self.fecha_nacimiento.into_into_dart().into_dart(),
            self.telefono.into_into_dart().into_dart(),
            self.email.into_into_dart().into_dart(),
            self.direccion.into_into_dart().into_dart(),
            self.notas_generales.into_into_dart().into_dart(),
            self.alergias.into_into_dart().into_dart(),
            self.condiciones_medicas.into_into_dart().into_dart(),
            self.fecha_registro.into_into_dart().into_dart(),
            self.activo.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::db::models::Paciente {}
impl flutter_rust_bridge::IntoIntoDart<crate::db::models::Paciente>
    for crate::db::models::Paciente
{
    fn into_into_dart(self) -> crate::db::models::Paciente {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::db::models::PaginatedPacientes {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.items.into_into_dart().into_dart(),
            self.total.into_into_dart().into_dart(),
            self.page.into_into_dart().into_dart(),
            self.page_size.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::db::models::PaginatedPacientes
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::db::models::PaginatedPacientes>
    for crate::db::models::PaginatedPacientes
{
    fn into_into_dart(self) -> crate::db::models::PaginatedPacientes {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::db::models::PaginatedSesiones {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.items.into_into_dart().into_dart(),
            self.total.into_into_dart().into_dart(),
            self.page.into_into_dart().into_dart(),
            self.page_size.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::db::models::PaginatedSesiones
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::db::models::PaginatedSesiones>
    for crate::db::models::PaginatedSesiones
{
    fn into_into_dart(self) -> crate::db::models::PaginatedSesiones {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::db::models::Sesion {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.paciente_id.into_into_dart().into_dart(),
            self.tratamiento_id.into_into_dart().into_dart(),
            self.fecha.into_into_dart().into_dart(),
            self.notas_sesion.into_into_dart().into_dart(),
            self.observaciones.into_into_dart().into_dart(),
            self.productos_usados.into_into_dart().into_dart(),
            self.precio_cobrado.into_into_dart().into_dart(),
            self.pagado.into_into_dart().into_dart(),
            self.created_at.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::db::models::Sesion {}
impl flutter_rust_bridge::IntoIntoDart<crate::db::models::Sesion> for crate::db::models::Sesion {
    fn into_into_dart(self) -> crate::db::models::Sesion {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::db::models::Tratamiento {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.nombre.into_into_dart().into_dart(),
            self.descripcion.into_into_dart().into_dart(),
            self.duracion_min.into_into_dart().into_dart(),
            self.precio.into_into_dart().into_dart(),
            self.activo.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::db::models::Tratamiento
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::db::models::Tratamiento>
    for crate::db::models::Tratamiento
{
    fn into_into_dart(self) -> crate::db::models::Tratamiento {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::db::models::ActualizarPaciente {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.nombre, serializer);
        <String>::sse_encode(self.apellido, serializer);
        <Option<String>>::sse_encode(self.fecha_nacimiento, serializer);
        <Option<String>>::sse_encode(self.telefono, serializer);
        <Option<String>>::sse_encode(self.email, serializer);
        <Option<String>>::sse_encode(self.direccion, serializer);
        <Option<String>>::sse_encode(self.notas_generales, serializer);
        <Option<String>>::sse_encode(self.alergias, serializer);
        <Option<String>>::sse_encode(self.condiciones_medicas, serializer);
    }
}

impl SseEncode for crate::db::models::ActualizarSesion {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.id, serializer);
        <Option<i64>>::sse_encode(self.tratamiento_id, serializer);
        <String>::sse_encode(self.fecha, serializer);
        <Option<String>>::sse_encode(self.notas_sesion, serializer);
        <Option<String>>::sse_encode(self.observaciones, serializer);
        <Option<String>>::sse_encode(self.productos_usados, serializer);
        <Option<f64>>::sse_encode(self.precio_cobrado, serializer);
        <bool>::sse_encode(self.pagado, serializer);
    }
}

impl SseEncode for crate::db::models::ActualizarTratamiento {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.nombre, serializer);
        <Option<String>>::sse_encode(self.descripcion, serializer);
        <Option<i64>>::sse_encode(self.duracion_min, serializer);
        <Option<f64>>::sse_encode(self.precio, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<crate::db::models::Paciente> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::db::models::Paciente>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::db::models::Sesion> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::db::models::Sesion>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::db::models::Tratamiento> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::db::models::Tratamiento>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::db::models::NuevaSesion {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.paciente_id, serializer);
        <Option<i64>>::sse_encode(self.tratamiento_id, serializer);
        <String>::sse_encode(self.fecha, serializer);
        <Option<String>>::sse_encode(self.notas_sesion, serializer);
        <Option<String>>::sse_encode(self.observaciones, serializer);
        <Option<String>>::sse_encode(self.productos_usados, serializer);
        <Option<f64>>::sse_encode(self.precio_cobrado, serializer);
        <bool>::sse_encode(self.pagado, serializer);
    }
}

impl SseEncode for crate::db::models::NuevoPaciente {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.nombre, serializer);
        <String>::sse_encode(self.apellido, serializer);
        <Option<String>>::sse_encode(self.fecha_nacimiento, serializer);
        <Option<String>>::sse_encode(self.telefono, serializer);
        <Option<String>>::sse_encode(self.email, serializer);
        <Option<String>>::sse_encode(self.direccion, serializer);
        <Option<String>>::sse_encode(self.notas_generales, serializer);
        <Option<String>>::sse_encode(self.alergias, serializer);
        <Option<String>>::sse_encode(self.condiciones_medicas, serializer);
    }
}

impl SseEncode for crate::db::models::NuevoTratamiento {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.nombre, serializer);
        <Option<String>>::sse_encode(self.descripcion, serializer);
        <Option<i64>>::sse_encode(self.duracion_min, serializer);
        <Option<f64>>::sse_encode(self.precio, serializer);
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <f64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <i64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::db::models::Paciente> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::db::models::Paciente>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::db::models::Sesion> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::db::models::Sesion>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::db::models::Paciente {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.nombre, serializer);
        <String>::sse_encode(self.apellido, serializer);
        <Option<String>>::sse_encode(self.fecha_nacimiento, serializer);
        <Option<String>>::sse_encode(self.telefono, serializer);
        <Option<String>>::sse_encode(self.email, serializer);
        <Option<String>>::sse_encode(self.direccion, serializer);
        <Option<String>>::sse_encode(self.notas_generales, serializer);
        <Option<String>>::sse_encode(self.alergias, serializer);
        <Option<String>>::sse_encode(self.condiciones_medicas, serializer);
        <String>::sse_encode(self.fecha_registro, serializer);
        <bool>::sse_encode(self.activo, serializer);
    }
}

impl SseEncode for crate::db::models::PaginatedPacientes {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::db::models::Paciente>>::sse_encode(self.items, serializer);
        <i64>::sse_encode(self.total, serializer);
        <i32>::sse_encode(self.page, serializer);
        <i32>::sse_encode(self.page_size, serializer);
    }
}

impl SseEncode for crate::db::models::PaginatedSesiones {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::db::models::Sesion>>::sse_encode(self.items, serializer);
        <i64>::sse_encode(self.total, serializer);
        <i32>::sse_encode(self.page, serializer);
        <i32>::sse_encode(self.page_size, serializer);
    }
}

impl SseEncode for crate::db::models::Sesion {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.id, serializer);
        <i64>::sse_encode(self.paciente_id, serializer);
        <Option<i64>>::sse_encode(self.tratamiento_id, serializer);
        <String>::sse_encode(self.fecha, serializer);
        <Option<String>>::sse_encode(self.notas_sesion, serializer);
        <Option<String>>::sse_encode(self.observaciones, serializer);
        <Option<String>>::sse_encode(self.productos_usados, serializer);
        <Option<f64>>::sse_encode(self.precio_cobrado, serializer);
        <bool>::sse_encode(self.pagado, serializer);
        <String>::sse_encode(self.created_at, serializer);
    }
}

impl SseEncode for crate::db::models::Tratamiento {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.nombre, serializer);
        <Option<String>>::sse_encode(self.descripcion, serializer);
        <Option<i64>>::sse_encode(self.duracion_min, serializer);
        <Option<f64>>::sse_encode(self.precio, serializer);
        <bool>::sse_encode(self.activo, serializer);
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
