// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/backup_api.dart';
import 'api/db_api.dart';
import 'api/import_api.dart';
import 'api/pdf_api.dart';
import 'api/photos_api.dart';
import 'api/server_api.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'db/error.dart';
import 'db/models.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 2129797442;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_datacare',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiPdfApiApiGeneratePatientReport({
    required PlatformInt64 pacienteId,
    required String outputPath,
  });

  Future<void> crateApiBackupApiCreateBackup({required String outputPath});

  Future<PlatformInt64> crateApiDbApiCreateGasto({required NuevoGasto gasto});

  Future<PlatformInt64> crateApiDbApiCreatePaciente({
    required NuevoPaciente paciente,
  });

  Future<PlatformInt64> crateApiDbApiCreateSesion({
    required NuevaSesion sesion,
  });

  Future<PlatformInt64> crateApiDbApiCreateTratamiento({
    required NuevoTratamiento tratamiento,
  });

  Future<void> crateApiDbApiDeactivatePaciente({required PlatformInt64 id});

  Future<void> crateApiDbApiDeleteGasto({required PlatformInt64 id});

  Future<void> crateApiPhotosApiDeletePhoto({required PlatformInt64 fotoId});

  Future<void> crateApiDbApiDeleteTratamiento({required PlatformInt64 id});

  Future<DashboardStats> crateApiDbApiGetDashboardStats();

  Future<Paciente?> crateApiDbApiGetPaciente({required PlatformInt64 id});

  Future<Sesion?> crateApiDbApiGetSesion({required PlatformInt64 id});

  Future<Tratamiento?> crateApiDbApiGetTratamiento({required PlatformInt64 id});

  String crateApiSimpleGreet({required String name});

  Future<ImportResult> crateApiImportApiImportPacientesFromExcel({
    required String filePath,
  });

  Future<void> crateApiSimpleInitApp();

  Future<void> crateApiDbApiInitDatabase({required String dbPath});

  Future<List<Gasto>> crateApiDbApiListGastos();

  Future<List<Sesion>> crateApiDbApiListIngresos();

  Future<PaginatedPacientes> crateApiDbApiListPacientes({
    String? search,
    required int page,
    required int pageSize,
  });

  Future<List<FotoSesion>> crateApiPhotosApiListPhotosByPatient({
    required PlatformInt64 pacienteId,
  });

  Future<List<FotoSesion>> crateApiPhotosApiListPhotosBySession({
    required PlatformInt64 sesionId,
  });

  Future<PaginatedSesiones> crateApiDbApiListSesionesByPaciente({
    required PlatformInt64 pacienteId,
    required int page,
    required int pageSize,
  });

  Future<List<Tratamiento>> crateApiDbApiListTratamientos();

  Future<void> crateApiBackupApiRestoreBackup({required String zipPath});

  Future<FotoSesion> crateApiPhotosApiSaveSessionPhoto({
    required PlatformInt64 pacienteId,
    required PlatformInt64 sesionId,
    required String inputPath,
    String? tipo,
    String? descripcion,
  });

  Future<void> crateApiServerApiStartLocalServer({required int port});

  Future<void> crateApiDbApiUpdateGasto({required Gasto gasto});

  Future<void> crateApiDbApiUpdatePaciente({
    required ActualizarPaciente paciente,
  });

  Future<void> crateApiDbApiUpdateSesion({required ActualizarSesion sesion});

  Future<void> crateApiDbApiUpdateTratamiento({
    required ActualizarTratamiento tratamiento,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AppError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AppError;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_AppErrorPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiPdfApiApiGeneratePatientReport({
    required PlatformInt64 pacienteId,
    required String outputPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(pacienteId, serializer);
          sse_encode_String(outputPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppError,
        ),
        constMeta: kCrateApiPdfApiApiGeneratePatientReportConstMeta,
        argValues: [pacienteId, outputPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPdfApiApiGeneratePatientReportConstMeta =>
      const TaskConstMeta(
        debugName: "api_generate_patient_report",
        argNames: ["pacienteId", "outputPath"],
      );

  @override
  Future<void> crateApiBackupApiCreateBackup({required String outputPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(outputPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBackupApiCreateBackupConstMeta,
        argValues: [outputPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBackupApiCreateBackupConstMeta =>
      const TaskConstMeta(debugName: "create_backup", argNames: ["outputPath"]);

  @override
  Future<PlatformInt64> crateApiDbApiCreateGasto({required NuevoGasto gasto}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_nuevo_gasto(gasto, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDbApiCreateGastoConstMeta,
        argValues: [gasto],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbApiCreateGastoConstMeta =>
      const TaskConstMeta(debugName: "create_gasto", argNames: ["gasto"]);

  @override
  Future<PlatformInt64> crateApiDbApiCreatePaciente({
    required NuevoPaciente paciente,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_nuevo_paciente(paciente, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDbApiCreatePacienteConstMeta,
        argValues: [paciente],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbApiCreatePacienteConstMeta =>
      const TaskConstMeta(debugName: "create_paciente", argNames: ["paciente"]);

  @override
  Future<PlatformInt64> crateApiDbApiCreateSesion({
    required NuevaSesion sesion,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_nueva_sesion(sesion, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDbApiCreateSesionConstMeta,
        argValues: [sesion],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbApiCreateSesionConstMeta =>
      const TaskConstMeta(debugName: "create_sesion", argNames: ["sesion"]);

  @override
  Future<PlatformInt64> crateApiDbApiCreateTratamiento({
    required NuevoTratamiento tratamiento,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_nuevo_tratamiento(tratamiento, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDbApiCreateTratamientoConstMeta,
        argValues: [tratamiento],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbApiCreateTratamientoConstMeta =>
      const TaskConstMeta(
        debugName: "create_tratamiento",
        argNames: ["tratamiento"],
      );

  @override
  Future<void> crateApiDbApiDeactivatePaciente({required PlatformInt64 id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDbApiDeactivatePacienteConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbApiDeactivatePacienteConstMeta =>
      const TaskConstMeta(debugName: "deactivate_paciente", argNames: ["id"]);

  @override
  Future<void> crateApiDbApiDeleteGasto({required PlatformInt64 id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDbApiDeleteGastoConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbApiDeleteGastoConstMeta =>
      const TaskConstMeta(debugName: "delete_gasto", argNames: ["id"]);

  @override
  Future<void> crateApiPhotosApiDeletePhoto({required PlatformInt64 fotoId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(fotoId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotosApiDeletePhotoConstMeta,
        argValues: [fotoId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotosApiDeletePhotoConstMeta =>
      const TaskConstMeta(debugName: "delete_photo", argNames: ["fotoId"]);

  @override
  Future<void> crateApiDbApiDeleteTratamiento({required PlatformInt64 id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDbApiDeleteTratamientoConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbApiDeleteTratamientoConstMeta =>
      const TaskConstMeta(debugName: "delete_tratamiento", argNames: ["id"]);

  @override
  Future<DashboardStats> crateApiDbApiGetDashboardStats() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_dashboard_stats,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDbApiGetDashboardStatsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbApiGetDashboardStatsConstMeta =>
      const TaskConstMeta(debugName: "get_dashboard_stats", argNames: []);

  @override
  Future<Paciente?> crateApiDbApiGetPaciente({required PlatformInt64 id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_paciente,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDbApiGetPacienteConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbApiGetPacienteConstMeta =>
      const TaskConstMeta(debugName: "get_paciente", argNames: ["id"]);

  @override
  Future<Sesion?> crateApiDbApiGetSesion({required PlatformInt64 id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_sesion,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDbApiGetSesionConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbApiGetSesionConstMeta =>
      const TaskConstMeta(debugName: "get_sesion", argNames: ["id"]);

  @override
  Future<Tratamiento?> crateApiDbApiGetTratamiento({
    required PlatformInt64 id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_tratamiento,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDbApiGetTratamientoConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbApiGetTratamientoConstMeta =>
      const TaskConstMeta(debugName: "get_tratamiento", argNames: ["id"]);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<ImportResult> crateApiImportApiImportPacientesFromExcel({
    required String filePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_import_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImportApiImportPacientesFromExcelConstMeta,
        argValues: [filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImportApiImportPacientesFromExcelConstMeta =>
      const TaskConstMeta(
        debugName: "import_pacientes_from_excel",
        argNames: ["filePath"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiDbApiInitDatabase({required String dbPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDbApiInitDatabaseConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbApiInitDatabaseConstMeta =>
      const TaskConstMeta(debugName: "init_database", argNames: ["dbPath"]);

  @override
  Future<List<Gasto>> crateApiDbApiListGastos() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_gasto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDbApiListGastosConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbApiListGastosConstMeta =>
      const TaskConstMeta(debugName: "list_gastos", argNames: []);

  @override
  Future<List<Sesion>> crateApiDbApiListIngresos() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_sesion,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDbApiListIngresosConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbApiListIngresosConstMeta =>
      const TaskConstMeta(debugName: "list_ingresos", argNames: []);

  @override
  Future<PaginatedPacientes> crateApiDbApiListPacientes({
    String? search,
    required int page,
    required int pageSize,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(search, serializer);
          sse_encode_i_32(page, serializer);
          sse_encode_i_32(pageSize, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_paginated_pacientes,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDbApiListPacientesConstMeta,
        argValues: [search, page, pageSize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbApiListPacientesConstMeta => const TaskConstMeta(
    debugName: "list_pacientes",
    argNames: ["search", "page", "pageSize"],
  );

  @override
  Future<List<FotoSesion>> crateApiPhotosApiListPhotosByPatient({
    required PlatformInt64 pacienteId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(pacienteId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_foto_sesion,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotosApiListPhotosByPatientConstMeta,
        argValues: [pacienteId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotosApiListPhotosByPatientConstMeta =>
      const TaskConstMeta(
        debugName: "list_photos_by_patient",
        argNames: ["pacienteId"],
      );

  @override
  Future<List<FotoSesion>> crateApiPhotosApiListPhotosBySession({
    required PlatformInt64 sesionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sesionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_foto_sesion,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotosApiListPhotosBySessionConstMeta,
        argValues: [sesionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotosApiListPhotosBySessionConstMeta =>
      const TaskConstMeta(
        debugName: "list_photos_by_session",
        argNames: ["sesionId"],
      );

  @override
  Future<PaginatedSesiones> crateApiDbApiListSesionesByPaciente({
    required PlatformInt64 pacienteId,
    required int page,
    required int pageSize,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(pacienteId, serializer);
          sse_encode_i_32(page, serializer);
          sse_encode_i_32(pageSize, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_paginated_sesiones,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDbApiListSesionesByPacienteConstMeta,
        argValues: [pacienteId, page, pageSize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbApiListSesionesByPacienteConstMeta =>
      const TaskConstMeta(
        debugName: "list_sesiones_by_paciente",
        argNames: ["pacienteId", "page", "pageSize"],
      );

  @override
  Future<List<Tratamiento>> crateApiDbApiListTratamientos() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_tratamiento,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDbApiListTratamientosConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbApiListTratamientosConstMeta =>
      const TaskConstMeta(debugName: "list_tratamientos", argNames: []);

  @override
  Future<void> crateApiBackupApiRestoreBackup({required String zipPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(zipPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBackupApiRestoreBackupConstMeta,
        argValues: [zipPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBackupApiRestoreBackupConstMeta =>
      const TaskConstMeta(debugName: "restore_backup", argNames: ["zipPath"]);

  @override
  Future<FotoSesion> crateApiPhotosApiSaveSessionPhoto({
    required PlatformInt64 pacienteId,
    required PlatformInt64 sesionId,
    required String inputPath,
    String? tipo,
    String? descripcion,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(pacienteId, serializer);
          sse_encode_i_64(sesionId, serializer);
          sse_encode_String(inputPath, serializer);
          sse_encode_opt_String(tipo, serializer);
          sse_encode_opt_String(descripcion, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_foto_sesion,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPhotosApiSaveSessionPhotoConstMeta,
        argValues: [pacienteId, sesionId, inputPath, tipo, descripcion],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPhotosApiSaveSessionPhotoConstMeta =>
      const TaskConstMeta(
        debugName: "save_session_photo",
        argNames: [
          "pacienteId",
          "sesionId",
          "inputPath",
          "tipo",
          "descripcion",
        ],
      );

  @override
  Future<void> crateApiServerApiStartLocalServer({required int port}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_16(port, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiServerApiStartLocalServerConstMeta,
        argValues: [port],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiServerApiStartLocalServerConstMeta =>
      const TaskConstMeta(debugName: "start_local_server", argNames: ["port"]);

  @override
  Future<void> crateApiDbApiUpdateGasto({required Gasto gasto}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_gasto(gasto, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDbApiUpdateGastoConstMeta,
        argValues: [gasto],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbApiUpdateGastoConstMeta =>
      const TaskConstMeta(debugName: "update_gasto", argNames: ["gasto"]);

  @override
  Future<void> crateApiDbApiUpdatePaciente({
    required ActualizarPaciente paciente,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_actualizar_paciente(paciente, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDbApiUpdatePacienteConstMeta,
        argValues: [paciente],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbApiUpdatePacienteConstMeta =>
      const TaskConstMeta(debugName: "update_paciente", argNames: ["paciente"]);

  @override
  Future<void> crateApiDbApiUpdateSesion({required ActualizarSesion sesion}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_actualizar_sesion(sesion, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDbApiUpdateSesionConstMeta,
        argValues: [sesion],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbApiUpdateSesionConstMeta =>
      const TaskConstMeta(debugName: "update_sesion", argNames: ["sesion"]);

  @override
  Future<void> crateApiDbApiUpdateTratamiento({
    required ActualizarTratamiento tratamiento,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_actualizar_tratamiento(
            tratamiento,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDbApiUpdateTratamientoConstMeta,
        argValues: [tratamiento],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbApiUpdateTratamientoConstMeta =>
      const TaskConstMeta(
        debugName: "update_tratamiento",
        argNames: ["tratamiento"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AppError => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AppError => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppError;

  @protected
  AppError
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AppErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AppError
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AppErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ActualizarPaciente dco_decode_actualizar_paciente(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return ActualizarPaciente(
      id: dco_decode_i_64(arr[0]),
      nombre: dco_decode_String(arr[1]),
      apellido: dco_decode_String(arr[2]),
      fechaNacimiento: dco_decode_opt_String(arr[3]),
      telefono: dco_decode_opt_String(arr[4]),
      email: dco_decode_opt_String(arr[5]),
      direccion: dco_decode_opt_String(arr[6]),
      notasGenerales: dco_decode_opt_String(arr[7]),
      alergias: dco_decode_opt_String(arr[8]),
      condicionesMedicas: dco_decode_opt_String(arr[9]),
    );
  }

  @protected
  ActualizarSesion dco_decode_actualizar_sesion(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return ActualizarSesion(
      id: dco_decode_i_64(arr[0]),
      tratamientoId: dco_decode_opt_box_autoadd_i_64(arr[1]),
      fecha: dco_decode_String(arr[2]),
      notasSesion: dco_decode_opt_String(arr[3]),
      observaciones: dco_decode_opt_String(arr[4]),
      productosUsados: dco_decode_opt_String(arr[5]),
      precioCobrado: dco_decode_opt_box_autoadd_f_64(arr[6]),
      pagado: dco_decode_bool(arr[7]),
    );
  }

  @protected
  ActualizarTratamiento dco_decode_actualizar_tratamiento(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ActualizarTratamiento(
      id: dco_decode_i_64(arr[0]),
      nombre: dco_decode_String(arr[1]),
      descripcion: dco_decode_opt_String(arr[2]),
      duracionMin: dco_decode_opt_box_autoadd_i_64(arr[3]),
      precio: dco_decode_opt_box_autoadd_f_64(arr[4]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ActualizarPaciente dco_decode_box_autoadd_actualizar_paciente(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_actualizar_paciente(raw);
  }

  @protected
  ActualizarSesion dco_decode_box_autoadd_actualizar_sesion(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_actualizar_sesion(raw);
  }

  @protected
  ActualizarTratamiento dco_decode_box_autoadd_actualizar_tratamiento(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_actualizar_tratamiento(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  Gasto dco_decode_box_autoadd_gasto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_gasto(raw);
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  NuevaSesion dco_decode_box_autoadd_nueva_sesion(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_nueva_sesion(raw);
  }

  @protected
  NuevoGasto dco_decode_box_autoadd_nuevo_gasto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_nuevo_gasto(raw);
  }

  @protected
  NuevoPaciente dco_decode_box_autoadd_nuevo_paciente(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_nuevo_paciente(raw);
  }

  @protected
  NuevoTratamiento dco_decode_box_autoadd_nuevo_tratamiento(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_nuevo_tratamiento(raw);
  }

  @protected
  Paciente dco_decode_box_autoadd_paciente(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_paciente(raw);
  }

  @protected
  Sesion dco_decode_box_autoadd_sesion(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_sesion(raw);
  }

  @protected
  Tratamiento dco_decode_box_autoadd_tratamiento(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_tratamiento(raw);
  }

  @protected
  DashboardStats dco_decode_dashboard_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DashboardStats(
      totalPacientesActivos: dco_decode_i_64(arr[0]),
      sesionesEsteMes: dco_decode_i_64(arr[1]),
      tratamientosRegistrados: dco_decode_i_64(arr[2]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FotoSesion dco_decode_foto_sesion(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return FotoSesion(
      id: dco_decode_i_64(arr[0]),
      sesionId: dco_decode_i_64(arr[1]),
      rutaFoto: dco_decode_String(arr[2]),
      rutaThumb: dco_decode_opt_String(arr[3]),
      tipo: dco_decode_opt_String(arr[4]),
      descripcion: dco_decode_opt_String(arr[5]),
      createdAt: dco_decode_String(arr[6]),
    );
  }

  @protected
  Gasto dco_decode_gasto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return Gasto(
      id: dco_decode_i_64(arr[0]),
      nombre: dco_decode_String(arr[1]),
      descripcion: dco_decode_opt_String(arr[2]),
      categoria: dco_decode_opt_String(arr[3]),
      monto: dco_decode_f_64(arr[4]),
      fecha: dco_decode_String(arr[5]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  ImportResult dco_decode_import_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ImportResult(
      total: dco_decode_i_64(arr[0]),
      exitos: dco_decode_i_64(arr[1]),
      sesionesCreadas: dco_decode_i_64(arr[2]),
      duplicados: dco_decode_i_64(arr[3]),
      errores: dco_decode_i_64(arr[4]),
      detalle: dco_decode_String(arr[5]),
    );
  }

  @protected
  List<FotoSesion> dco_decode_list_foto_sesion(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_foto_sesion).toList();
  }

  @protected
  List<Gasto> dco_decode_list_gasto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_gasto).toList();
  }

  @protected
  List<Paciente> dco_decode_list_paciente(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_paciente).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<Sesion> dco_decode_list_sesion(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_sesion).toList();
  }

  @protected
  List<Tratamiento> dco_decode_list_tratamiento(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_tratamiento).toList();
  }

  @protected
  NuevaSesion dco_decode_nueva_sesion(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return NuevaSesion(
      pacienteId: dco_decode_i_64(arr[0]),
      tratamientoId: dco_decode_opt_box_autoadd_i_64(arr[1]),
      fecha: dco_decode_String(arr[2]),
      notasSesion: dco_decode_opt_String(arr[3]),
      observaciones: dco_decode_opt_String(arr[4]),
      productosUsados: dco_decode_opt_String(arr[5]),
      precioCobrado: dco_decode_opt_box_autoadd_f_64(arr[6]),
      pagado: dco_decode_bool(arr[7]),
    );
  }

  @protected
  NuevoGasto dco_decode_nuevo_gasto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return NuevoGasto(
      nombre: dco_decode_String(arr[0]),
      descripcion: dco_decode_opt_String(arr[1]),
      categoria: dco_decode_opt_String(arr[2]),
      monto: dco_decode_f_64(arr[3]),
      fecha: dco_decode_String(arr[4]),
    );
  }

  @protected
  NuevoPaciente dco_decode_nuevo_paciente(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return NuevoPaciente(
      nombre: dco_decode_String(arr[0]),
      apellido: dco_decode_String(arr[1]),
      fechaNacimiento: dco_decode_opt_String(arr[2]),
      telefono: dco_decode_opt_String(arr[3]),
      email: dco_decode_opt_String(arr[4]),
      direccion: dco_decode_opt_String(arr[5]),
      notasGenerales: dco_decode_opt_String(arr[6]),
      alergias: dco_decode_opt_String(arr[7]),
      condicionesMedicas: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  NuevoTratamiento dco_decode_nuevo_tratamiento(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return NuevoTratamiento(
      nombre: dco_decode_String(arr[0]),
      descripcion: dco_decode_opt_String(arr[1]),
      duracionMin: dco_decode_opt_box_autoadd_i_64(arr[2]),
      precio: dco_decode_opt_box_autoadd_f_64(arr[3]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  Paciente? dco_decode_opt_box_autoadd_paciente(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_paciente(raw);
  }

  @protected
  Sesion? dco_decode_opt_box_autoadd_sesion(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_sesion(raw);
  }

  @protected
  Tratamiento? dco_decode_opt_box_autoadd_tratamiento(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_tratamiento(raw);
  }

  @protected
  Paciente dco_decode_paciente(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return Paciente(
      id: dco_decode_i_64(arr[0]),
      nombre: dco_decode_String(arr[1]),
      apellido: dco_decode_String(arr[2]),
      fechaNacimiento: dco_decode_opt_String(arr[3]),
      telefono: dco_decode_opt_String(arr[4]),
      email: dco_decode_opt_String(arr[5]),
      direccion: dco_decode_opt_String(arr[6]),
      notasGenerales: dco_decode_opt_String(arr[7]),
      alergias: dco_decode_opt_String(arr[8]),
      condicionesMedicas: dco_decode_opt_String(arr[9]),
      fechaRegistro: dco_decode_String(arr[10]),
      activo: dco_decode_bool(arr[11]),
    );
  }

  @protected
  PaginatedPacientes dco_decode_paginated_pacientes(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PaginatedPacientes(
      items: dco_decode_list_paciente(arr[0]),
      total: dco_decode_i_64(arr[1]),
      page: dco_decode_i_32(arr[2]),
      pageSize: dco_decode_i_32(arr[3]),
    );
  }

  @protected
  PaginatedSesiones dco_decode_paginated_sesiones(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PaginatedSesiones(
      items: dco_decode_list_sesion(arr[0]),
      total: dco_decode_i_64(arr[1]),
      page: dco_decode_i_32(arr[2]),
      pageSize: dco_decode_i_32(arr[3]),
    );
  }

  @protected
  Sesion dco_decode_sesion(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return Sesion(
      id: dco_decode_i_64(arr[0]),
      pacienteId: dco_decode_i_64(arr[1]),
      tratamientoId: dco_decode_opt_box_autoadd_i_64(arr[2]),
      fecha: dco_decode_String(arr[3]),
      notasSesion: dco_decode_opt_String(arr[4]),
      observaciones: dco_decode_opt_String(arr[5]),
      productosUsados: dco_decode_opt_String(arr[6]),
      precioCobrado: dco_decode_opt_box_autoadd_f_64(arr[7]),
      pagado: dco_decode_bool(arr[8]),
      createdAt: dco_decode_String(arr[9]),
    );
  }

  @protected
  Tratamiento dco_decode_tratamiento(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return Tratamiento(
      id: dco_decode_i_64(arr[0]),
      nombre: dco_decode_String(arr[1]),
      descripcion: dco_decode_opt_String(arr[2]),
      duracionMin: dco_decode_opt_box_autoadd_i_64(arr[3]),
      precio: dco_decode_opt_box_autoadd_f_64(arr[4]),
      activo: dco_decode_bool(arr[5]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AppError
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AppErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AppError
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AppErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ActualizarPaciente sse_decode_actualizar_paciente(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_nombre = sse_decode_String(deserializer);
    var var_apellido = sse_decode_String(deserializer);
    var var_fechaNacimiento = sse_decode_opt_String(deserializer);
    var var_telefono = sse_decode_opt_String(deserializer);
    var var_email = sse_decode_opt_String(deserializer);
    var var_direccion = sse_decode_opt_String(deserializer);
    var var_notasGenerales = sse_decode_opt_String(deserializer);
    var var_alergias = sse_decode_opt_String(deserializer);
    var var_condicionesMedicas = sse_decode_opt_String(deserializer);
    return ActualizarPaciente(
      id: var_id,
      nombre: var_nombre,
      apellido: var_apellido,
      fechaNacimiento: var_fechaNacimiento,
      telefono: var_telefono,
      email: var_email,
      direccion: var_direccion,
      notasGenerales: var_notasGenerales,
      alergias: var_alergias,
      condicionesMedicas: var_condicionesMedicas,
    );
  }

  @protected
  ActualizarSesion sse_decode_actualizar_sesion(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_tratamientoId = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_fecha = sse_decode_String(deserializer);
    var var_notasSesion = sse_decode_opt_String(deserializer);
    var var_observaciones = sse_decode_opt_String(deserializer);
    var var_productosUsados = sse_decode_opt_String(deserializer);
    var var_precioCobrado = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_pagado = sse_decode_bool(deserializer);
    return ActualizarSesion(
      id: var_id,
      tratamientoId: var_tratamientoId,
      fecha: var_fecha,
      notasSesion: var_notasSesion,
      observaciones: var_observaciones,
      productosUsados: var_productosUsados,
      precioCobrado: var_precioCobrado,
      pagado: var_pagado,
    );
  }

  @protected
  ActualizarTratamiento sse_decode_actualizar_tratamiento(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_nombre = sse_decode_String(deserializer);
    var var_descripcion = sse_decode_opt_String(deserializer);
    var var_duracionMin = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_precio = sse_decode_opt_box_autoadd_f_64(deserializer);
    return ActualizarTratamiento(
      id: var_id,
      nombre: var_nombre,
      descripcion: var_descripcion,
      duracionMin: var_duracionMin,
      precio: var_precio,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ActualizarPaciente sse_decode_box_autoadd_actualizar_paciente(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_actualizar_paciente(deserializer));
  }

  @protected
  ActualizarSesion sse_decode_box_autoadd_actualizar_sesion(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_actualizar_sesion(deserializer));
  }

  @protected
  ActualizarTratamiento sse_decode_box_autoadd_actualizar_tratamiento(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_actualizar_tratamiento(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  Gasto sse_decode_box_autoadd_gasto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_gasto(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  NuevaSesion sse_decode_box_autoadd_nueva_sesion(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_nueva_sesion(deserializer));
  }

  @protected
  NuevoGasto sse_decode_box_autoadd_nuevo_gasto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_nuevo_gasto(deserializer));
  }

  @protected
  NuevoPaciente sse_decode_box_autoadd_nuevo_paciente(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_nuevo_paciente(deserializer));
  }

  @protected
  NuevoTratamiento sse_decode_box_autoadd_nuevo_tratamiento(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_nuevo_tratamiento(deserializer));
  }

  @protected
  Paciente sse_decode_box_autoadd_paciente(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_paciente(deserializer));
  }

  @protected
  Sesion sse_decode_box_autoadd_sesion(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_sesion(deserializer));
  }

  @protected
  Tratamiento sse_decode_box_autoadd_tratamiento(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_tratamiento(deserializer));
  }

  @protected
  DashboardStats sse_decode_dashboard_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_totalPacientesActivos = sse_decode_i_64(deserializer);
    var var_sesionesEsteMes = sse_decode_i_64(deserializer);
    var var_tratamientosRegistrados = sse_decode_i_64(deserializer);
    return DashboardStats(
      totalPacientesActivos: var_totalPacientesActivos,
      sesionesEsteMes: var_sesionesEsteMes,
      tratamientosRegistrados: var_tratamientosRegistrados,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FotoSesion sse_decode_foto_sesion(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_sesionId = sse_decode_i_64(deserializer);
    var var_rutaFoto = sse_decode_String(deserializer);
    var var_rutaThumb = sse_decode_opt_String(deserializer);
    var var_tipo = sse_decode_opt_String(deserializer);
    var var_descripcion = sse_decode_opt_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    return FotoSesion(
      id: var_id,
      sesionId: var_sesionId,
      rutaFoto: var_rutaFoto,
      rutaThumb: var_rutaThumb,
      tipo: var_tipo,
      descripcion: var_descripcion,
      createdAt: var_createdAt,
    );
  }

  @protected
  Gasto sse_decode_gasto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_nombre = sse_decode_String(deserializer);
    var var_descripcion = sse_decode_opt_String(deserializer);
    var var_categoria = sse_decode_opt_String(deserializer);
    var var_monto = sse_decode_f_64(deserializer);
    var var_fecha = sse_decode_String(deserializer);
    return Gasto(
      id: var_id,
      nombre: var_nombre,
      descripcion: var_descripcion,
      categoria: var_categoria,
      monto: var_monto,
      fecha: var_fecha,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  ImportResult sse_decode_import_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_total = sse_decode_i_64(deserializer);
    var var_exitos = sse_decode_i_64(deserializer);
    var var_sesionesCreadas = sse_decode_i_64(deserializer);
    var var_duplicados = sse_decode_i_64(deserializer);
    var var_errores = sse_decode_i_64(deserializer);
    var var_detalle = sse_decode_String(deserializer);
    return ImportResult(
      total: var_total,
      exitos: var_exitos,
      sesionesCreadas: var_sesionesCreadas,
      duplicados: var_duplicados,
      errores: var_errores,
      detalle: var_detalle,
    );
  }

  @protected
  List<FotoSesion> sse_decode_list_foto_sesion(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FotoSesion>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_foto_sesion(deserializer));
    }
    return ans_;
  }

  @protected
  List<Gasto> sse_decode_list_gasto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Gasto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_gasto(deserializer));
    }
    return ans_;
  }

  @protected
  List<Paciente> sse_decode_list_paciente(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Paciente>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_paciente(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<Sesion> sse_decode_list_sesion(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Sesion>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_sesion(deserializer));
    }
    return ans_;
  }

  @protected
  List<Tratamiento> sse_decode_list_tratamiento(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Tratamiento>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_tratamiento(deserializer));
    }
    return ans_;
  }

  @protected
  NuevaSesion sse_decode_nueva_sesion(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pacienteId = sse_decode_i_64(deserializer);
    var var_tratamientoId = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_fecha = sse_decode_String(deserializer);
    var var_notasSesion = sse_decode_opt_String(deserializer);
    var var_observaciones = sse_decode_opt_String(deserializer);
    var var_productosUsados = sse_decode_opt_String(deserializer);
    var var_precioCobrado = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_pagado = sse_decode_bool(deserializer);
    return NuevaSesion(
      pacienteId: var_pacienteId,
      tratamientoId: var_tratamientoId,
      fecha: var_fecha,
      notasSesion: var_notasSesion,
      observaciones: var_observaciones,
      productosUsados: var_productosUsados,
      precioCobrado: var_precioCobrado,
      pagado: var_pagado,
    );
  }

  @protected
  NuevoGasto sse_decode_nuevo_gasto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nombre = sse_decode_String(deserializer);
    var var_descripcion = sse_decode_opt_String(deserializer);
    var var_categoria = sse_decode_opt_String(deserializer);
    var var_monto = sse_decode_f_64(deserializer);
    var var_fecha = sse_decode_String(deserializer);
    return NuevoGasto(
      nombre: var_nombre,
      descripcion: var_descripcion,
      categoria: var_categoria,
      monto: var_monto,
      fecha: var_fecha,
    );
  }

  @protected
  NuevoPaciente sse_decode_nuevo_paciente(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nombre = sse_decode_String(deserializer);
    var var_apellido = sse_decode_String(deserializer);
    var var_fechaNacimiento = sse_decode_opt_String(deserializer);
    var var_telefono = sse_decode_opt_String(deserializer);
    var var_email = sse_decode_opt_String(deserializer);
    var var_direccion = sse_decode_opt_String(deserializer);
    var var_notasGenerales = sse_decode_opt_String(deserializer);
    var var_alergias = sse_decode_opt_String(deserializer);
    var var_condicionesMedicas = sse_decode_opt_String(deserializer);
    return NuevoPaciente(
      nombre: var_nombre,
      apellido: var_apellido,
      fechaNacimiento: var_fechaNacimiento,
      telefono: var_telefono,
      email: var_email,
      direccion: var_direccion,
      notasGenerales: var_notasGenerales,
      alergias: var_alergias,
      condicionesMedicas: var_condicionesMedicas,
    );
  }

  @protected
  NuevoTratamiento sse_decode_nuevo_tratamiento(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nombre = sse_decode_String(deserializer);
    var var_descripcion = sse_decode_opt_String(deserializer);
    var var_duracionMin = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_precio = sse_decode_opt_box_autoadd_f_64(deserializer);
    return NuevoTratamiento(
      nombre: var_nombre,
      descripcion: var_descripcion,
      duracionMin: var_duracionMin,
      precio: var_precio,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Paciente? sse_decode_opt_box_autoadd_paciente(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_paciente(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Sesion? sse_decode_opt_box_autoadd_sesion(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_sesion(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Tratamiento? sse_decode_opt_box_autoadd_tratamiento(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_tratamiento(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Paciente sse_decode_paciente(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_nombre = sse_decode_String(deserializer);
    var var_apellido = sse_decode_String(deserializer);
    var var_fechaNacimiento = sse_decode_opt_String(deserializer);
    var var_telefono = sse_decode_opt_String(deserializer);
    var var_email = sse_decode_opt_String(deserializer);
    var var_direccion = sse_decode_opt_String(deserializer);
    var var_notasGenerales = sse_decode_opt_String(deserializer);
    var var_alergias = sse_decode_opt_String(deserializer);
    var var_condicionesMedicas = sse_decode_opt_String(deserializer);
    var var_fechaRegistro = sse_decode_String(deserializer);
    var var_activo = sse_decode_bool(deserializer);
    return Paciente(
      id: var_id,
      nombre: var_nombre,
      apellido: var_apellido,
      fechaNacimiento: var_fechaNacimiento,
      telefono: var_telefono,
      email: var_email,
      direccion: var_direccion,
      notasGenerales: var_notasGenerales,
      alergias: var_alergias,
      condicionesMedicas: var_condicionesMedicas,
      fechaRegistro: var_fechaRegistro,
      activo: var_activo,
    );
  }

  @protected
  PaginatedPacientes sse_decode_paginated_pacientes(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_items = sse_decode_list_paciente(deserializer);
    var var_total = sse_decode_i_64(deserializer);
    var var_page = sse_decode_i_32(deserializer);
    var var_pageSize = sse_decode_i_32(deserializer);
    return PaginatedPacientes(
      items: var_items,
      total: var_total,
      page: var_page,
      pageSize: var_pageSize,
    );
  }

  @protected
  PaginatedSesiones sse_decode_paginated_sesiones(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_items = sse_decode_list_sesion(deserializer);
    var var_total = sse_decode_i_64(deserializer);
    var var_page = sse_decode_i_32(deserializer);
    var var_pageSize = sse_decode_i_32(deserializer);
    return PaginatedSesiones(
      items: var_items,
      total: var_total,
      page: var_page,
      pageSize: var_pageSize,
    );
  }

  @protected
  Sesion sse_decode_sesion(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_pacienteId = sse_decode_i_64(deserializer);
    var var_tratamientoId = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_fecha = sse_decode_String(deserializer);
    var var_notasSesion = sse_decode_opt_String(deserializer);
    var var_observaciones = sse_decode_opt_String(deserializer);
    var var_productosUsados = sse_decode_opt_String(deserializer);
    var var_precioCobrado = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_pagado = sse_decode_bool(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    return Sesion(
      id: var_id,
      pacienteId: var_pacienteId,
      tratamientoId: var_tratamientoId,
      fecha: var_fecha,
      notasSesion: var_notasSesion,
      observaciones: var_observaciones,
      productosUsados: var_productosUsados,
      precioCobrado: var_precioCobrado,
      pagado: var_pagado,
      createdAt: var_createdAt,
    );
  }

  @protected
  Tratamiento sse_decode_tratamiento(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_nombre = sse_decode_String(deserializer);
    var var_descripcion = sse_decode_opt_String(deserializer);
    var var_duracionMin = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_precio = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_activo = sse_decode_bool(deserializer);
    return Tratamiento(
      id: var_id,
      nombre: var_nombre,
      descripcion: var_descripcion,
      duracionMin: var_duracionMin,
      precio: var_precio,
      activo: var_activo,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppError(
    AppError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AppErrorImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppError(
    AppError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AppErrorImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_actualizar_paciente(
    ActualizarPaciente self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.nombre, serializer);
    sse_encode_String(self.apellido, serializer);
    sse_encode_opt_String(self.fechaNacimiento, serializer);
    sse_encode_opt_String(self.telefono, serializer);
    sse_encode_opt_String(self.email, serializer);
    sse_encode_opt_String(self.direccion, serializer);
    sse_encode_opt_String(self.notasGenerales, serializer);
    sse_encode_opt_String(self.alergias, serializer);
    sse_encode_opt_String(self.condicionesMedicas, serializer);
  }

  @protected
  void sse_encode_actualizar_sesion(
    ActualizarSesion self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_opt_box_autoadd_i_64(self.tratamientoId, serializer);
    sse_encode_String(self.fecha, serializer);
    sse_encode_opt_String(self.notasSesion, serializer);
    sse_encode_opt_String(self.observaciones, serializer);
    sse_encode_opt_String(self.productosUsados, serializer);
    sse_encode_opt_box_autoadd_f_64(self.precioCobrado, serializer);
    sse_encode_bool(self.pagado, serializer);
  }

  @protected
  void sse_encode_actualizar_tratamiento(
    ActualizarTratamiento self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.nombre, serializer);
    sse_encode_opt_String(self.descripcion, serializer);
    sse_encode_opt_box_autoadd_i_64(self.duracionMin, serializer);
    sse_encode_opt_box_autoadd_f_64(self.precio, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_actualizar_paciente(
    ActualizarPaciente self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_actualizar_paciente(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_actualizar_sesion(
    ActualizarSesion self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_actualizar_sesion(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_actualizar_tratamiento(
    ActualizarTratamiento self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_actualizar_tratamiento(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_gasto(Gasto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_gasto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_nueva_sesion(
    NuevaSesion self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_nueva_sesion(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_nuevo_gasto(
    NuevoGasto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_nuevo_gasto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_nuevo_paciente(
    NuevoPaciente self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_nuevo_paciente(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_nuevo_tratamiento(
    NuevoTratamiento self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_nuevo_tratamiento(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_paciente(
    Paciente self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_paciente(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_sesion(Sesion self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_sesion(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_tratamiento(
    Tratamiento self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_tratamiento(self, serializer);
  }

  @protected
  void sse_encode_dashboard_stats(
    DashboardStats self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.totalPacientesActivos, serializer);
    sse_encode_i_64(self.sesionesEsteMes, serializer);
    sse_encode_i_64(self.tratamientosRegistrados, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_foto_sesion(FotoSesion self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_i_64(self.sesionId, serializer);
    sse_encode_String(self.rutaFoto, serializer);
    sse_encode_opt_String(self.rutaThumb, serializer);
    sse_encode_opt_String(self.tipo, serializer);
    sse_encode_opt_String(self.descripcion, serializer);
    sse_encode_String(self.createdAt, serializer);
  }

  @protected
  void sse_encode_gasto(Gasto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.nombre, serializer);
    sse_encode_opt_String(self.descripcion, serializer);
    sse_encode_opt_String(self.categoria, serializer);
    sse_encode_f_64(self.monto, serializer);
    sse_encode_String(self.fecha, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_import_result(ImportResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.total, serializer);
    sse_encode_i_64(self.exitos, serializer);
    sse_encode_i_64(self.sesionesCreadas, serializer);
    sse_encode_i_64(self.duplicados, serializer);
    sse_encode_i_64(self.errores, serializer);
    sse_encode_String(self.detalle, serializer);
  }

  @protected
  void sse_encode_list_foto_sesion(
    List<FotoSesion> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_foto_sesion(item, serializer);
    }
  }

  @protected
  void sse_encode_list_gasto(List<Gasto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_gasto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_paciente(List<Paciente> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_paciente(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_sesion(List<Sesion> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_sesion(item, serializer);
    }
  }

  @protected
  void sse_encode_list_tratamiento(
    List<Tratamiento> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_tratamiento(item, serializer);
    }
  }

  @protected
  void sse_encode_nueva_sesion(NuevaSesion self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.pacienteId, serializer);
    sse_encode_opt_box_autoadd_i_64(self.tratamientoId, serializer);
    sse_encode_String(self.fecha, serializer);
    sse_encode_opt_String(self.notasSesion, serializer);
    sse_encode_opt_String(self.observaciones, serializer);
    sse_encode_opt_String(self.productosUsados, serializer);
    sse_encode_opt_box_autoadd_f_64(self.precioCobrado, serializer);
    sse_encode_bool(self.pagado, serializer);
  }

  @protected
  void sse_encode_nuevo_gasto(NuevoGasto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.nombre, serializer);
    sse_encode_opt_String(self.descripcion, serializer);
    sse_encode_opt_String(self.categoria, serializer);
    sse_encode_f_64(self.monto, serializer);
    sse_encode_String(self.fecha, serializer);
  }

  @protected
  void sse_encode_nuevo_paciente(NuevoPaciente self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.nombre, serializer);
    sse_encode_String(self.apellido, serializer);
    sse_encode_opt_String(self.fechaNacimiento, serializer);
    sse_encode_opt_String(self.telefono, serializer);
    sse_encode_opt_String(self.email, serializer);
    sse_encode_opt_String(self.direccion, serializer);
    sse_encode_opt_String(self.notasGenerales, serializer);
    sse_encode_opt_String(self.alergias, serializer);
    sse_encode_opt_String(self.condicionesMedicas, serializer);
  }

  @protected
  void sse_encode_nuevo_tratamiento(
    NuevoTratamiento self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.nombre, serializer);
    sse_encode_opt_String(self.descripcion, serializer);
    sse_encode_opt_box_autoadd_i_64(self.duracionMin, serializer);
    sse_encode_opt_box_autoadd_f_64(self.precio, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_paciente(
    Paciente? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_paciente(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_sesion(
    Sesion? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_sesion(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_tratamiento(
    Tratamiento? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_tratamiento(self, serializer);
    }
  }

  @protected
  void sse_encode_paciente(Paciente self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.nombre, serializer);
    sse_encode_String(self.apellido, serializer);
    sse_encode_opt_String(self.fechaNacimiento, serializer);
    sse_encode_opt_String(self.telefono, serializer);
    sse_encode_opt_String(self.email, serializer);
    sse_encode_opt_String(self.direccion, serializer);
    sse_encode_opt_String(self.notasGenerales, serializer);
    sse_encode_opt_String(self.alergias, serializer);
    sse_encode_opt_String(self.condicionesMedicas, serializer);
    sse_encode_String(self.fechaRegistro, serializer);
    sse_encode_bool(self.activo, serializer);
  }

  @protected
  void sse_encode_paginated_pacientes(
    PaginatedPacientes self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_paciente(self.items, serializer);
    sse_encode_i_64(self.total, serializer);
    sse_encode_i_32(self.page, serializer);
    sse_encode_i_32(self.pageSize, serializer);
  }

  @protected
  void sse_encode_paginated_sesiones(
    PaginatedSesiones self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_sesion(self.items, serializer);
    sse_encode_i_64(self.total, serializer);
    sse_encode_i_32(self.page, serializer);
    sse_encode_i_32(self.pageSize, serializer);
  }

  @protected
  void sse_encode_sesion(Sesion self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_i_64(self.pacienteId, serializer);
    sse_encode_opt_box_autoadd_i_64(self.tratamientoId, serializer);
    sse_encode_String(self.fecha, serializer);
    sse_encode_opt_String(self.notasSesion, serializer);
    sse_encode_opt_String(self.observaciones, serializer);
    sse_encode_opt_String(self.productosUsados, serializer);
    sse_encode_opt_box_autoadd_f_64(self.precioCobrado, serializer);
    sse_encode_bool(self.pagado, serializer);
    sse_encode_String(self.createdAt, serializer);
  }

  @protected
  void sse_encode_tratamiento(Tratamiento self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.nombre, serializer);
    sse_encode_opt_String(self.descripcion, serializer);
    sse_encode_opt_box_autoadd_i_64(self.duracionMin, serializer);
    sse_encode_opt_box_autoadd_f_64(self.precio, serializer);
    sse_encode_bool(self.activo, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class AppErrorImpl extends RustOpaque implements AppError {
  // Not to be used by end users
  AppErrorImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  AppErrorImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_AppError,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_AppError,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_AppErrorPtr,
  );
}
