[package]
name = "rust_lib_datacare"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
anyhow = "1.0.104"
axum = { version = "0.8.9", features = ["multipart"] }
calamine = "0.36.1"
chrono = "0.4.45"
env_logger = "0.11.11"
flutter_rust_bridge = "=2.12.0"
image = "0.25.10"
log = "0.4.33"
printpdf = "0.5"
rusqlite = { version = "0.40.2", features = ["bundled"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["full"] }
tower-http = { version = "0.7.0", features = ["cors", "fs"] }
uuid = { version = "1.24.1", features = ["v4"] }
zip = "8.6.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
