// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../db/models.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> initDatabase({required String dbPath}) =>
    RustLib.instance.api.crateApiDbApiInitDatabase(dbPath: dbPath);

Future<PlatformInt64> createPaciente({required NuevoPaciente paciente}) =>
    RustLib.instance.api.crateApiDbApiCreatePaciente(paciente: paciente);

Future<PaginatedPacientes> listPacientes({
  String? search,
  required int page,
  required int pageSize,
}) => RustLib.instance.api.crateApiDbApiListPacientes(
  search: search,
  page: page,
  pageSize: pageSize,
);

Future<Paciente?> getPaciente({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiDbApiGetPaciente(id: id);

Future<void> updatePaciente({required ActualizarPaciente paciente}) =>
    RustLib.instance.api.crateApiDbApiUpdatePaciente(paciente: paciente);

Future<void> deactivatePaciente({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiDbApiDeactivatePaciente(id: id);

Future<PlatformInt64> createTratamiento({
  required NuevoTratamiento tratamiento,
}) => RustLib.instance.api.crateApiDbApiCreateTratamiento(
  tratamiento: tratamiento,
);

Future<List<Tratamiento>> listTratamientos() =>
    RustLib.instance.api.crateApiDbApiListTratamientos();

Future<void> updateTratamiento({required ActualizarTratamiento tratamiento}) =>
    RustLib.instance.api.crateApiDbApiUpdateTratamiento(
      tratamiento: tratamiento,
    );

Future<PlatformInt64> createSesion({required NuevaSesion sesion}) =>
    RustLib.instance.api.crateApiDbApiCreateSesion(sesion: sesion);

Future<PaginatedSesiones> listSesionesByPaciente({
  required PlatformInt64 pacienteId,
  required int page,
  required int pageSize,
}) => RustLib.instance.api.crateApiDbApiListSesionesByPaciente(
  pacienteId: pacienteId,
  page: page,
  pageSize: pageSize,
);

Future<Sesion?> getSesion({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiDbApiGetSesion(id: id);

Future<void> updateSesion({required ActualizarSesion sesion}) =>
    RustLib.instance.api.crateApiDbApiUpdateSesion(sesion: sesion);

Future<DashboardStats> getDashboardStats() =>
    RustLib.instance.api.crateApiDbApiGetDashboardStats();
