// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<ImportResult> importPacientesFromExcel({required String filePath}) =>
    RustLib.instance.api.crateApiImportApiImportPacientesFromExcel(
      filePath: filePath,
    );

class ImportResult {
  final PlatformInt64 total;
  final PlatformInt64 exitos;
  final PlatformInt64 errores;
  final String detalle;

  const ImportResult({
    required this.total,
    required this.exitos,
    required this.errores,
    required this.detalle,
  });

  @override
  int get hashCode =>
      total.hashCode ^ exitos.hashCode ^ errores.hashCode ^ detalle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportResult &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          exitos == other.exitos &&
          errores == other.errores &&
          detalle == other.detalle;
}
