// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../db/models.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_photo_manager`

Future<FotoSesion> saveSessionPhoto({
  required PlatformInt64 pacienteId,
  required PlatformInt64 sesionId,
  required String inputPath,
  String? tipo,
  String? descripcion,
}) => RustLib.instance.api.crateApiPhotosApiSaveSessionPhoto(
  pacienteId: pacienteId,
  sesionId: sesionId,
  inputPath: inputPath,
  tipo: tipo,
  descripcion: descripcion,
);

Future<void> deletePhoto({required PlatformInt64 fotoId}) =>
    RustLib.instance.api.crateApiPhotosApiDeletePhoto(fotoId: fotoId);

Future<List<FotoSesion>> listPhotosBySession({
  required PlatformInt64 sesionId,
}) => RustLib.instance.api.crateApiPhotosApiListPhotosBySession(
  sesionId: sesionId,
);
