// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ActualizarPaciente {
  final PlatformInt64 id;
  final String nombre;
  final String apellido;
  final String? fechaNacimiento;
  final String? telefono;
  final String? email;
  final String? direccion;
  final String? notasGenerales;
  final String? alergias;
  final String? condicionesMedicas;

  const ActualizarPaciente({
    required this.id,
    required this.nombre,
    required this.apellido,
    this.fechaNacimiento,
    this.telefono,
    this.email,
    this.direccion,
    this.notasGenerales,
    this.alergias,
    this.condicionesMedicas,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      nombre.hashCode ^
      apellido.hashCode ^
      fechaNacimiento.hashCode ^
      telefono.hashCode ^
      email.hashCode ^
      direccion.hashCode ^
      notasGenerales.hashCode ^
      alergias.hashCode ^
      condicionesMedicas.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ActualizarPaciente &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          nombre == other.nombre &&
          apellido == other.apellido &&
          fechaNacimiento == other.fechaNacimiento &&
          telefono == other.telefono &&
          email == other.email &&
          direccion == other.direccion &&
          notasGenerales == other.notasGenerales &&
          alergias == other.alergias &&
          condicionesMedicas == other.condicionesMedicas;
}

class ActualizarSesion {
  final PlatformInt64 id;
  final PlatformInt64? tratamientoId;
  final String fecha;
  final String? notasSesion;
  final String? observaciones;
  final String? productosUsados;
  final double? precioCobrado;
  final bool pagado;

  const ActualizarSesion({
    required this.id,
    this.tratamientoId,
    required this.fecha,
    this.notasSesion,
    this.observaciones,
    this.productosUsados,
    this.precioCobrado,
    required this.pagado,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      tratamientoId.hashCode ^
      fecha.hashCode ^
      notasSesion.hashCode ^
      observaciones.hashCode ^
      productosUsados.hashCode ^
      precioCobrado.hashCode ^
      pagado.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ActualizarSesion &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          tratamientoId == other.tratamientoId &&
          fecha == other.fecha &&
          notasSesion == other.notasSesion &&
          observaciones == other.observaciones &&
          productosUsados == other.productosUsados &&
          precioCobrado == other.precioCobrado &&
          pagado == other.pagado;
}

class ActualizarTratamiento {
  final PlatformInt64 id;
  final String nombre;
  final String? descripcion;
  final PlatformInt64? duracionMin;
  final double? precio;

  const ActualizarTratamiento({
    required this.id,
    required this.nombre,
    this.descripcion,
    this.duracionMin,
    this.precio,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      nombre.hashCode ^
      descripcion.hashCode ^
      duracionMin.hashCode ^
      precio.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ActualizarTratamiento &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          nombre == other.nombre &&
          descripcion == other.descripcion &&
          duracionMin == other.duracionMin &&
          precio == other.precio;
}

class NuevaSesion {
  final PlatformInt64 pacienteId;
  final PlatformInt64? tratamientoId;
  final String fecha;
  final String? notasSesion;
  final String? observaciones;
  final String? productosUsados;
  final double? precioCobrado;
  final bool pagado;

  const NuevaSesion({
    required this.pacienteId,
    this.tratamientoId,
    required this.fecha,
    this.notasSesion,
    this.observaciones,
    this.productosUsados,
    this.precioCobrado,
    required this.pagado,
  });

  @override
  int get hashCode =>
      pacienteId.hashCode ^
      tratamientoId.hashCode ^
      fecha.hashCode ^
      notasSesion.hashCode ^
      observaciones.hashCode ^
      productosUsados.hashCode ^
      precioCobrado.hashCode ^
      pagado.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NuevaSesion &&
          runtimeType == other.runtimeType &&
          pacienteId == other.pacienteId &&
          tratamientoId == other.tratamientoId &&
          fecha == other.fecha &&
          notasSesion == other.notasSesion &&
          observaciones == other.observaciones &&
          productosUsados == other.productosUsados &&
          precioCobrado == other.precioCobrado &&
          pagado == other.pagado;
}

class NuevoPaciente {
  final String nombre;
  final String apellido;
  final String? fechaNacimiento;
  final String? telefono;
  final String? email;
  final String? direccion;
  final String? notasGenerales;
  final String? alergias;
  final String? condicionesMedicas;

  const NuevoPaciente({
    required this.nombre,
    required this.apellido,
    this.fechaNacimiento,
    this.telefono,
    this.email,
    this.direccion,
    this.notasGenerales,
    this.alergias,
    this.condicionesMedicas,
  });

  @override
  int get hashCode =>
      nombre.hashCode ^
      apellido.hashCode ^
      fechaNacimiento.hashCode ^
      telefono.hashCode ^
      email.hashCode ^
      direccion.hashCode ^
      notasGenerales.hashCode ^
      alergias.hashCode ^
      condicionesMedicas.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NuevoPaciente &&
          runtimeType == other.runtimeType &&
          nombre == other.nombre &&
          apellido == other.apellido &&
          fechaNacimiento == other.fechaNacimiento &&
          telefono == other.telefono &&
          email == other.email &&
          direccion == other.direccion &&
          notasGenerales == other.notasGenerales &&
          alergias == other.alergias &&
          condicionesMedicas == other.condicionesMedicas;
}

class NuevoTratamiento {
  final String nombre;
  final String? descripcion;
  final PlatformInt64? duracionMin;
  final double? precio;

  const NuevoTratamiento({
    required this.nombre,
    this.descripcion,
    this.duracionMin,
    this.precio,
  });

  @override
  int get hashCode =>
      nombre.hashCode ^
      descripcion.hashCode ^
      duracionMin.hashCode ^
      precio.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NuevoTratamiento &&
          runtimeType == other.runtimeType &&
          nombre == other.nombre &&
          descripcion == other.descripcion &&
          duracionMin == other.duracionMin &&
          precio == other.precio;
}

class Paciente {
  final PlatformInt64 id;
  final String nombre;
  final String apellido;
  final String? fechaNacimiento;
  final String? telefono;
  final String? email;
  final String? direccion;
  final String? notasGenerales;
  final String? alergias;
  final String? condicionesMedicas;
  final String fechaRegistro;
  final bool activo;

  const Paciente({
    required this.id,
    required this.nombre,
    required this.apellido,
    this.fechaNacimiento,
    this.telefono,
    this.email,
    this.direccion,
    this.notasGenerales,
    this.alergias,
    this.condicionesMedicas,
    required this.fechaRegistro,
    required this.activo,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      nombre.hashCode ^
      apellido.hashCode ^
      fechaNacimiento.hashCode ^
      telefono.hashCode ^
      email.hashCode ^
      direccion.hashCode ^
      notasGenerales.hashCode ^
      alergias.hashCode ^
      condicionesMedicas.hashCode ^
      fechaRegistro.hashCode ^
      activo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Paciente &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          nombre == other.nombre &&
          apellido == other.apellido &&
          fechaNacimiento == other.fechaNacimiento &&
          telefono == other.telefono &&
          email == other.email &&
          direccion == other.direccion &&
          notasGenerales == other.notasGenerales &&
          alergias == other.alergias &&
          condicionesMedicas == other.condicionesMedicas &&
          fechaRegistro == other.fechaRegistro &&
          activo == other.activo;
}

class PaginatedPacientes {
  final List<Paciente> items;
  final PlatformInt64 total;
  final int page;
  final int pageSize;

  const PaginatedPacientes({
    required this.items,
    required this.total,
    required this.page,
    required this.pageSize,
  });

  @override
  int get hashCode =>
      items.hashCode ^ total.hashCode ^ page.hashCode ^ pageSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PaginatedPacientes &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          total == other.total &&
          page == other.page &&
          pageSize == other.pageSize;
}

class PaginatedSesiones {
  final List<Sesion> items;
  final PlatformInt64 total;
  final int page;
  final int pageSize;

  const PaginatedSesiones({
    required this.items,
    required this.total,
    required this.page,
    required this.pageSize,
  });

  @override
  int get hashCode =>
      items.hashCode ^ total.hashCode ^ page.hashCode ^ pageSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PaginatedSesiones &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          total == other.total &&
          page == other.page &&
          pageSize == other.pageSize;
}

class Sesion {
  final PlatformInt64 id;
  final PlatformInt64 pacienteId;
  final PlatformInt64? tratamientoId;
  final String fecha;
  final String? notasSesion;
  final String? observaciones;
  final String? productosUsados;
  final double? precioCobrado;
  final bool pagado;
  final String createdAt;

  const Sesion({
    required this.id,
    required this.pacienteId,
    this.tratamientoId,
    required this.fecha,
    this.notasSesion,
    this.observaciones,
    this.productosUsados,
    this.precioCobrado,
    required this.pagado,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      pacienteId.hashCode ^
      tratamientoId.hashCode ^
      fecha.hashCode ^
      notasSesion.hashCode ^
      observaciones.hashCode ^
      productosUsados.hashCode ^
      precioCobrado.hashCode ^
      pagado.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Sesion &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          pacienteId == other.pacienteId &&
          tratamientoId == other.tratamientoId &&
          fecha == other.fecha &&
          notasSesion == other.notasSesion &&
          observaciones == other.observaciones &&
          productosUsados == other.productosUsados &&
          precioCobrado == other.precioCobrado &&
          pagado == other.pagado &&
          createdAt == other.createdAt;
}

class Tratamiento {
  final PlatformInt64 id;
  final String nombre;
  final String? descripcion;
  final PlatformInt64? duracionMin;
  final double? precio;
  final bool activo;

  const Tratamiento({
    required this.id,
    required this.nombre,
    this.descripcion,
    this.duracionMin,
    this.precio,
    required this.activo,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      nombre.hashCode ^
      descripcion.hashCode ^
      duracionMin.hashCode ^
      precio.hashCode ^
      activo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Tratamiento &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          nombre == other.nombre &&
          descripcion == other.descripcion &&
          duracionMin == other.duracionMin &&
          precio == other.precio &&
          activo == other.activo;
}
